##################################################################################
# Cloudify Diamond plugin definition.
##################################################################################

plugins:
    diamond:
        executor: host_agent
        source: https://github.com/junaid-ali/cloudify-diamond-plugin/archive/1.3.18.dev0.zip
        package_name: cloudify-diamond-plugin
        package_version: '1.3.18.dev0'
        install: false
